site_name: AWS Lambda Client (ALC)
site_url: https://alc.syngenta-digital.com
theme:
    name: material
    logo: https://avatars.githubusercontent.com/u/65528694?s=200&v=4
    palette:
        -
            media: "(prefers-color-scheme: light)"
            scheme: syngenta-light
            toggle:
                icon: material/weather-night
                name: Dark Mode
        -
            media: "(prefers-color-scheme: dark)"
            scheme: syngenta-dark
            toggle:
                icon: material/weather-sunny
                name: Light Mode
    highlightjs: true
    hljs_languages:
        - python
        - javascript
        - yml
    shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s
extra_css:
    - css/custom.css

### colors ###
# blue: #01004C
# green: #70D979
# text: white
# dark mode:
    # bg: blue
    # text: white
    # links: green

# light mode:
    # bg: white
    # text: blue
    # links: green
