site_name: AWS Lambda Client (ALC)
site_url: https://alc.syngenta-digital.com
site_author: Syngenta Digital
nav:
    - Home: index.md
    - Node:
        - node/install.md
        - Event Handler:
            - APIGateway:
                - node/apigateway/index.md
                - Router:
                    - node/apigateway/router/setup.md
                    - node/apigateway/router/configurations.md
                - EndPoint:
                    - node/apigateway/endpoint/setup.md
                    - node/apigateway/endpoint/configurations.md
                - node/apigateway/request.md
                - node/apigateway/response.md
            - DynamoDB:
                - node/dynamodb/index.md
                - node/dynamodb/configurations.md
                - node/dynamodb/record.md
    - Python:
        - python/install.md
    - Rust:
        - rust/install.md
    - Typescript:
        - typescript/install.md
theme:
    name: material
    logo: https://avatars.githubusercontent.com/u/65528694?s=200&v=4
    palette:
        -
            media: "(prefers-color-scheme: light)"
            scheme: syngenta-light
            toggle:
                icon: material/weather-night
                name: Dark Mode
        -
            media: "(prefers-color-scheme: dark)"
            scheme: syngenta-dark
            toggle:
                icon: material/weather-sunny
                name: Light Mode
    highlightjs: true
    hljs_languages:
        - python
        - javascript
        - yml
    shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s
    features:
        - navigation.top
        - navigation.instant
        - navigation.indexes
        - navigation.tracking
        - content.code.annotate
markdown_extensions:
    - codehilite
    - meta
    - admonition
    - pymdownx.details
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight:
        linenums: true
    - pymdownx.snippets:
        base_path: "."
        check_paths: true
    - toc:
        permalink: true
        toc_depth: 4
    - pymdownx.superfences:
        custom_fences:
            -
                name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
    - search
    - markdownextradata
extra:
    web:
        url: http://127.0.0.1:8000
extra_css:
    - extra.css

### colors ###
# blue: #01004C
# green: #70D979
# text: white
# dark mode:
    # bg: blue
    # text: white
    # links: green

# light mode:
    # bg: white
    # text: blue
    # links: green
